services:
  prometheus:
    image: prom/prometheus:v3.0.0
    volumes:
      - ./prometheus:/etc/prometheus
      - metrics_data:/prometheus
    ports:
      - 9090:9090
    restart:
      unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle' 

  grafana:
    image: grafana/grafana:11.3.1
    volumes:
      - ./grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart:
      unless-stopped

volumes:
  metrics_data:
    external: true
  grafana_data:
    external: true
