services:
  prometheus:
    image: prom/prometheus:v3.0.0
    volumes:
      - ./prometheus:/etc/prometheus
      - metrics_data:/prometheus
    ports:
      - 9090:9090
    restart:
      unless-stopped
    
  grafana:
    image: grafana/grafana:11.3.1
    volumes:
      - ./grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart:
      unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    ports:
      - 9100:9100
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
    restart:
      unless-stopped

volumes:
  metrics_data:
  grafana_data:
